Attempt to prepare autobuild subsystem for the Linz server
git-svn-id: https://dev.geogebra.org/svn/trunk/geogebra@10494 23ce0884-8a58-47d3-bc5c-ddf1cd5b9f9e

diff --git a/scripts/autobuild/windows/WiX/create-msi b/scripts/autobuild/windows/WiX/create-msi
--- a/scripts/autobuild/windows/WiX/create-msi
+++ b/scripts/autobuild/windows/WiX/create-msi
@@ -1,5 +1,12 @@
 #!/bin/sh
-WIXDIR=../wix
+
+WIXDIR=../wix36 # You can override this by using a default value in autobuild.conf
+
+test -r ../../autobuild.conf || {
+ echo "Cannot find ../../autobuild.conf (make sure you edit autobuild.conf.dist first)"
+ exit 1
+ }
+. ../.../autobuild.conf
 
 test -r $WIXDIR/candle.exe || {
  echo WiX is not installed into $WIXDIR
@@ -25,8 +32,16 @@ GGBVERSION=`cat ../../../../build/unpacked/version.txt`
 GGBVERSION_DASHED=`echo $GGBVERSION | tr . -`
 MSIFILE=GeoGebra-Windows-Installer-$GGBVERSION_DASHED.msi
 
-wine $WIXDIR/candle.exe GeoGebra.wxs
-wine $WIXDIR/light.exe -sval -ext WixUIExtension GeoGebra.wixobj
+wine $WIXDIR/candle.exe GeoGebra.wxs -dcodepage=1252
+wine $WIXDIR/light.exe -sval -ext WixUIExtension -cultures:en-us -out GeoGebra.msi GeoGebra.wixobj
+
+# Creating localized installers (http://wix.tramontana.co.hu/tutorial/transforms/morphing-installers)
+cat languages.txt | while read CULTURE CODEPAGE; do
+ wine $WIXDIR/candle.exe GeoGebra.wxs -dcodepage=$CODEPAGE
+ wine $WIXDIR/light.exe -sval -ext WixUIExtension -cultures:$CULTURE -out GeoGebra_$CULTURE.msi GeoGebra.wixobj
+ wine $WIXDIR/torch.exe -p -t language GeoGebra.msi GeoGebra_$CULTURE.msi -out $CULTURE.mst
+ wine $WIXDIR/EmbedTransform.exe GeoGebra.msi $CULTURE.mst
+ done
 
 mv GeoGebra.msi $MSIFILE
 
